<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[@id='page']</description>
   <name>Footer_Logo_Incorrect_Object</name>
   <tag></tag>
   <elementGuidId>a2685658-c235-437f-b894-3e36cc1f71ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
